Representing Systems of Equations as Matrices

1.1 - System of Linear Equations
A system of linear equations (or linear system) is a collection of one or more linear equations involving the same variables. For example:

−𝑥1+3𝑥2=7 ,
 3𝑥1+2𝑥2=1,

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
A1 = np.array(
    [
    [-1 , 3],
    [3 , 2] 
    ],
    dtype = np.dtype(float)

)

b1 = np.array([7 ,1] , dtype = np.dtype(float))



In [7]:
print(f"Matrix A : \n {A1}")
print(f"b is : {b1}")

Matrix A : 
 [[-1.  3.]
 [ 3.  2.]]
b is : [7. 1.]


In [ ]:
# Shape of A1 and b1
print(np.shape(A1))
print(np.shape(b1))

(2, 2)
(2,)


In [ ]:
#Solving A1 and b1
system_A1 = np.linalg.solve(A1, b1)
print(system_A1)

[-1.  2.]


In [10]:
A1_det = np.linalg.det(A1)
print(A1_det)

-11.000000000000002


# Representation of the system as a matrix
Now we have to stack these metrices, using hstack() method.

We have to reshape b using b1.reshape(-1 , 1)
-1 : automatically figure out the number of elements in matrix
1 : There should be exactly one column

It reshape the b from [7 , 1] to [[7], [1]] two rows and 1 column.

In [12]:
system_A1_matrix = np.hstack((A1 , b1.reshape(-1 , 1)))
print(system_A1_matrix)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


3 - System of Linear Equations with No Solutions
Given another system of linear equations:

−𝑥1+3𝑥2=7,
3𝑥1−9𝑥2=1,

In [24]:
A2 = np.array([
    [-1 , 3],
    [3 , -9]
    ],
    dtype = np.dtype(float)

)

b2 = np.array([7 , 1] , dtype = np.dtype(float))

print(f"Matrix A2 : {A2}")
print(f"Matrix b2 : {b2}")

Matrix A2 : [[-1.  3.]
 [ 3. -9.]]
Matrix b2 : [7. 1.]


In [25]:
print(A2.shape)
print(b2.shape)

(2, 2)
(2,)


In [27]:
try:
    system_A2 = np.linalg.solve(A2 , b2)
    print(system_A2)
except np.linalg.LinAlgError as err:
    print(err)


Singular matrix


In [28]:
system_A2_matrix = np.hstack((A2 , b2.reshape(-1 , 1)))
print(system_A2_matrix)

[[-1.  3.  7.]
 [ 3. -9.  1.]]


4 - System of Linear Equations with an Infinite Number of Solutions
By changing the free coefficients of the system  (2)
 , you can bring it to consistency:

−𝑥1+3𝑥2=7,
3𝑥1−9𝑥2=−21,

In [18]:
A3 = np.array([
    [-1 , 3],
    [3 , -9]
    ],
    dtype = np.dtype(float)

)

b3 = np.array([7 , 21], dtype = np.dtype(float))

In [23]:
try:
    system_A3 = np.linalg.solve(A3, b3)
    print(system_A3)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


Creating matric by using hstack()

In [29]:
system_A3_matrix = np.hstack((A3 , b3.reshape(-1 , 1)))
print(system_A3_matrix)

[[-1.  3.  7.]
 [ 3. -9. 21.]]
